# Generated by Django 2.2.16 on 2022-09-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220928_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientlink',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингридиенты в рецепте', 'verbose_name_plural': 'Ингридиенты в рецепте'},
        ),
    ]
